version: '3'

services:
  payload:
    build:
      context: .
      args:
        # Must be anything except "production" otherwise dev dependencies will not be installed.
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/node/app/src
      - ./.env:/home/node/app/.env
      - ./.eslintrc.json:/home/node/app/.eslintrc.json
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./credentials:/home/node/app/credentials
    command: sh -c "npm run dev"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
