apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: itmayziii-api
  namespace: '117906996620'
  selfLink: /apis/serving.knative.dev/v1/namespaces/117906996620/services/itmayziii-api
  uid: 3024ee81-1903-446f-876e-c92e9a193637
  resourceVersion: AAYHXqamkk8
  generation: 3
  creationTimestamp: '2023-10-10T15:22:37.069833Z'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: tommymay37@gmail.com
    serving.knative.dev/lastModifier: tommymay37@gmail.com
    run.googleapis.com/operation-id: 5f651075-6a96-4d17-9228-8e4a285764e4
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/ingress-status: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 2ae990c6-99b5-4aaf-a63d-afef31bc9f76
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/sessionAffinity: 'true'
        run.googleapis.com/vpc-access-egress: all-traffic
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/vpc-access-connector: projects/itmayziii/locations/us-central1/connectors/cloudrun-uscentral1
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: app-itmayziii-api@itmayziii.iam.gserviceaccount.com
      containers:
        - image: us-central1-docker.pkg.dev/itmayziii/docker-us-central1/itmayziii-api@sha256:66dfb3b7d8aa81d46294162db65a92fd6c351a45f9c3ab84b899a82484e2c7f2
          ports:
            - name: http1
              containerPort: 3000
          env:
            - name: APP_ENV
              value: production
            - name: NODE_ENV
              value: production
            - name: MEDIA_URL
              value: https://tommymay.dev
            - name: CSRF_DOMAINS
              value: https://cms.tommymay.dev
            - name: GOOGLE_STATIC_MAPS_KEY
              value: AIzaSyAxoqsoaBOp4ebT44y4y8ApbRDyAYLi5TE
            - name: GOOGLE_RECAPTCHA_SITE_KEY
              value: 6LdCoY4oAAAAAKDcokcIgxgAZakByK1m9XVDo2O3
            - name: GCS_BUCKET
              value: tommy-may-dev
            - name: EMAIL_API_TOPIC
              value: send-email
            - name: EMAIL_FROM
              value: no-reply@tommymay.dev
            - name: EMAIL_FROM_NAME
              value: tommymay.dev
            - name: MG_DOMAIN
              value: mg.tommymay.dev
            - name: CONTACT_EMAIL
              value: contacttommymay@gmail.com
            - name: GOOGLE_PROJECT_ID
              value: itmayziii
            - name: PAYLOAD_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: itmayziii-api-payload-secret
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: mongodb-atlas-serverlessinstance0-admin-uri
            - name: GOOGLE_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: google-url-signing-secret
            - name: MG_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: mailgun-api-key-mg-tommymay-dev
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000
  traffic:
    - percent: 100
      latestRevision: true
status:
  observedGeneration: 3
  conditions:
    - type: Ready
      status: 'True'
      lastTransitionTime: '2023-10-10T15:49:24.448981Z'
    - type: ConfigurationsReady
      status: 'True'
      lastTransitionTime: '2023-10-10T15:48:51.861805Z'
    - type: RoutesReady
      status: 'True'
      lastTransitionTime: '2023-10-10T15:49:24.518479Z'
  latestReadyRevisionName: itmayziii-api-00003-h5s
  latestCreatedRevisionName: itmayziii-api-00003-h5s
  traffic:
    - revisionName: itmayziii-api-00003-h5s
      percent: 100
      latestRevision: true
  url: https://itmayziii-api-3ng3os4swq-uc.a.run.app
  address:
    url: https://itmayziii-api-3ng3os4swq-uc.a.run.app
