steps:
  - id: 'docker-build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/docker-us-central1/$REPO_NAME:$TAG_NAME',
      '--build-arg',
      'NO_COLOR=true'
      '.'
    ]
    waitFor: ['-'] # Run immediately

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-us-central1/$REPO_NAME:$TAG_NAME'

options:
  logging: 'CLOUD_LOGGING_ONLY'
tags: ['app-itmayziii-api', 'docker', 'build']
timeout: '600s' # 10 minutes
