steps:
  - id: 'docker-build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME',
      '.'
    ]
    waitFor: ['-'] # Run immediately

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'

options:
  logging: 'CLOUD_LOGGING_ONLY'
tags: ['app-itmayziii-api', 'docker', 'build']
timeout: '600s' # 10 minutes
