apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: itmayziii-api-cloud-run
description: Production delivery pipeline for itmayziii-api.
serialPipeline:
  stages:
    - targetId: cloud-run-us-central1

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cloud-run-us-central1
description: Cloud run target for us-central1 region.
run:
  location: projects/itmayziii/locations/us-central1
