apiVersion: 'serving.knative.dev/v1'
kind: 'Service'
metadata:
  name: 'itmayziii-api'
  labels:
    cloud.googleapis.com/location: 'us-central1'
  annotations:
    run.googleapis.com/description: 'CMS powered by Payload CMS and Node.js.'
    run.googleapis.com/ingress: 'internal-and-cloud-load-balancing'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/sessionAffinity: 'true'
        run.googleapis.com/vpc-access-egress: 'all-traffic'
        run.googleapis.com/vpc-access-connector: 'projects/itmayziii/locations/us-central1/connectors/cloudrun-uscentral1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 'app-itmayziii-api@itmayziii.iam.gserviceaccount.com'
      containers:
        - image: 'us-central1-docker.pkg.dev/itmayziii/docker-us-central1/itmayziii-api'
          ports:
            - name: 'http1'
              containerPort: 3000
          env:
            - name: 'APP_ENV'
              value: 'production'
            - name: 'NODE_ENV'
              value: 'production'
            - name: 'MEDIA_URL'
              value: 'https://tommymay.dev'
            - name: 'CSRF_DOMAINS'
              value: 'https://cms.tommymay.dev'
            - name: 'GOOGLE_STATIC_MAPS_KEY'
              value: 'AIzaSyAxoqsoaBOp4ebT44y4y8ApbRDyAYLi5TE'
            - name: 'GOOGLE_RECAPTCHA_SITE_KEY'
              value: '6LdCoY4oAAAAAKDcokcIgxgAZakByK1m9XVDo2O3'
            - name: 'GCS_BUCKET'
              value: 'tommy-may-dev'
            - name: 'EMAIL_API_TOPIC'
              value: 'send-email'
            - name: 'EMAIL_FROM'
              value: 'no-reply@tommymay.dev'
            - name: 'EMAIL_FROM_NAME'
              value: 'tommymay.dev'
            - name: 'MG_DOMAIN'
              value: 'mg.tommymay.dev'
            - name: 'CONTACT_EMAIL'
              value: 'contacttommymay@gmail.com'
            - name: 'GOOGLE_PROJECT_ID'
              value: 'itmayziii'
            - name: 'PAYLOAD_SECRET'
              valueFrom:
                secretKeyRef:
                  key: 'latest'
                  name: 'itmayziii-api-payload-secret'
            - name: 'MONGODB_URI'
              valueFrom:
                secretKeyRef:
                  key: 'latest'
                  name: 'mongodb-atlas-serverlessinstance0-admin-uri'
            - name: 'GOOGLE_SIGNING_SECRET'
              valueFrom:
                secretKeyRef:
                  key: 'latest'
                  name: 'google-url-signing-secret'
            - name: 'MG_KEY'
              valueFrom:
                secretKeyRef:
                  key: 'latest'
                  name: 'mailgun-api-key-mg-tommymay-dev'
          resources:
            limits:
              cpu: '1000m'
              memory: '512Mi'
          livenessProbe:
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              path: '/api/health'
              port: 3000
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000
