apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: itmayziii-api
manifests:
  rawYaml:
    - service.yaml
deploy:
  # Recommend you leave the empty {}. Cloud Deploy populates this during rendering, based on the project
  # and location from the target definition.
  cloudrun: {}
