apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: itmayziii-api
manifests:
  rawYaml:
    - service.yaml
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  local:
    push: true
  platforms:
    - linux/amd64
  artifacts:
    - image: us-central1-docker.pkg.dev/itmayziii/docker-us-central1/itmayziii-api
      context: .
      docker: {}
deploy:
  cloudrun:
    projectid: itmayziii
    region: us-central1
